import type { AiProfile } from './schema';

export const AI_PROFILES: Record<string, AiProfile> = {
  easy: {
    id: 'easy',
    thinkInterval: 2.5,
    incomeMultiplier: 0.7,
    startGold: 60,
    maxQueue: 2,
    goldReserve: 40,
    threatDistance: 18,
    aggressionRatio: 1.6,
    roleMix: { melee: 0.7, ranged: 0.25, tank: 0.05 },
    reactivity: 0.3,
    randomness: 0.5,
    buyUpgrades: false,
    seed: 11,
  },
  normal: {
    id: 'normal',
    thinkInterval: 1.5,
    incomeMultiplier: 1,
    startGold: 100,
    maxQueue: 3,
    goldReserve: 20,
    threatDistance: 22,
    aggressionRatio: 1.3,
    roleMix: { melee: 0.5, ranged: 0.3, tank: 0.2 },
    reactivity: 0.6,
    randomness: 0.25,
    buyUpgrades: true,
    seed: 22,
  },
  hard: {
    id: 'hard',
    thinkInterval: 0.8,
    incomeMultiplier: 1.3,
    startGold: 140,
    maxQueue: 4,
    goldReserve: 0,
    threatDistance: 26,
    aggressionRatio: 1.15,
    roleMix: { melee: 0.4, ranged: 0.35, tank: 0.25 },
    reactivity: 1,
    randomness: 0.1,
    buyUpgrades: true,
    seed: 33,
  },
};
