import type { UnitDef } from './schema';

/** Unit roster. Add a unit here, list it in an age (ages.ts) and register its model key. */
export const UNITS: Record<string, UnitDef> = {
  soldier: {
    id: 'soldier',
    name: 'Soldier',
    role: 'melee',
    modelKey: 'unit.soldier',
    cost: 25,
    spawnTime: 2.5,
    maxHealth: 100,
    speed: 3.2,
    radius: 0.45,
    detectionRange: 12,
    attack: { damage: 12, range: 1.6, cooldown: 0.8 },
    muzzleHeight: 1.2,
    aimHeight: 1.2,
    goldReward: 14,
    xpReward: 20,
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    role: 'ranged',
    modelKey: 'unit.archer',
    cost: 35,
    spawnTime: 3.5,
    maxHealth: 60,
    speed: 3.0,
    radius: 0.4,
    detectionRange: 14,
    attack: { damage: 10, range: 11, cooldown: 1.2, projectileId: 'arrow' },
    muzzleHeight: 1.5,
    aimHeight: 1.1,
    goldReward: 20,
    xpReward: 30,
  },
  brute: {
    id: 'brute',
    name: 'Brute',
    role: 'tank',
    modelKey: 'unit.brute',
    cost: 80,
    spawnTime: 6,
    maxHealth: 350,
    speed: 2.4,
    radius: 0.7,
    detectionRange: 12,
    attack: { damage: 28, range: 1.9, cooldown: 1.3 },
    muzzleHeight: 1.6,
    aimHeight: 1.5,
    goldReward: 50,
    xpReward: 70,
  },
};
